### ISSUE TITLE
Unexpected response from server

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium-sender#17]
I can't setup the app. I always get an error in the url field: "Unexpected response from server".

Server version: 0.48.5

**Comment by zadam** [comment]
Hi, can you provide the logs from both client and server?

**Comment by Myzel394** [comment]
Nevermind, found out it was an issue with [bunkerized-nginx](https://github.com/bunkerity/bunkerized-nginx). You have to add:

```
WHITELIST_USER_AGENT=okhttp
```

to the environmental variables
