### ISSUE TITLE
Can't do anything

### ISSUE THREAD

**Issue by pinq-** [zadam/trilium-sender#20]
After install from play store I only get this view: 
![image](https://user-images.githubusercontent.com/10464992/177386391-3011eacf-90bb-4c4c-b462-48d3174457ee.png)

I set the right settings ( I use yunohost to host trilium) and it says everything is ok, but after that nothing happens. I can only see this view. I can't move anything or to anything. 
I use android 12 and sony zx1 compact.

**Comment by zadam** [comment]
Hi, it kind of explains it on that screen - the main app is only for setup, you then use it by adding a "Add note" shortcut or through sharing (links/images) with the app.

Just to make sure we're on the same page, this is a very limited application used for sending content to trilium, it's not a full working Trilium app for android.

**Comment by zadam** [comment]
The "add note" shortcut must be added as an android launcher button. Long press on your launcher to add shortcut and there it should be available.

**Comment by pinq-** [comment]
Now I found it! Thanks.
