### ISSUE TITLE
Note isn't created as protected

### ISSUE THREAD

**Issue by Rainerr123** [zadam/trilium-sender#21]
i have my journal set to protected subtree and adding new notes on desktop are protected however if added via the android app then it isn't created protected

**Comment by zadam** [comment]
Yeah, this is expected. To be able to create a protected note, app needs to have a "session" which means the encryption key derived from the password. But when sending from Android app this is not available so the note cannot be encrypted.

**Comment by Rainerr123** [comment]
ofcourse! stupid me, makes complete sense.
