### ISSUE TITLE
trilium sender setup - it wants a username?!

### ISSUE THREAD

**Issue by glennrice** [zadam/trilium-sender#22]
I might be missing something here but what username is trilium sender wanting in its setup?

Trilium Server never set one up, not prompts for one. Entering random text doesn't work either 😀

**Comment by zadam** [comment]
Hello, earlier versions of Trilium used to have username, and it's kept there for now for backwards compatibility.

However, entering random string should work - the username is not checked on the server.

**Comment by glennrice** [comment]
Thanks. No wonder I couldn't find reference to a username anywhere!
